services:
  backend:
    build: 
      context: ./backend
      target: ${APP_ENV:-}
    container_name: feature-request-system-be
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
      - /var/www/html/node_modules
      - /var/www/html/public/build
    networks:
      - app-network
    
  frontend:
    build: 
      context: ./frontend 
      target: ${VITE_APP_ENV:-}
    container_name: feature-request-system-fe
    ports:
      - "${FE_PORT:-5173}:${CONTAINER_PORT:-80}"      
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/dist
    networks:
      - app-network
    depends_on:
      - backend
    

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
